
function tbl = readConditioningData(filename, varargin)

    tbl = tablex.fromFile( ...
        filename ...
        , "trim", false ...
        , "convertTo", @double ...
        , "replaceMissing", true ...
        , varargin{:} ...
    );

end%

