
function tbl = readConditioningPlan(filename, varargin)

    tbl = tablex.fromFile( ...
        filename ...
        , "trim", false ...
        , "convertTo", @string ...
        , "replaceMissing", true ...
        , varargin{:} ...
    );

end%

