
function tbl = toFile(tbl, fileName, varargin)

    tbl = timetable2table(tbl);
    tbl = convertvars(tbl, "Time", @string);

    writetable( ...
        tbl, fileName, ...
        "writeRowNames", false, ...
        "writeVariableNames", true, ...
        varargin{:} ...
    );

end%

