classdef (Abstract) BEARExporter < handle

    methods (Abstract)

        writeEstimationInfo(obj, data)
        writeActualFitted(obj, data)
        writeResids(obj, data)
        writeSteadyState(obj, data)
        writeIRF(obj, data)
        writeForecasts(obj, data)
        writeFEVD(obj, data)
        writeHistDecomposition(obj, data)
        writeCondForecasts(obj, data)
        writeStruct_Shocks(obj, data)
        writeHistDecomp(obj, data)
        writeFavarIRF(obj, data)
        writeFavarFEVD(obj, data)
        writeFavarHistDecomp(obj, data)
        writeTimeVariation(obj, data)
        writeLocalMeanEstimates(obj, data)
        writeFavarIRFTimeVariation(obj, data)
        writePredExo(obj, data)
        writeIRFTimeVariation(obj, data)
        writeFEVDResValues(obj, data)
        writeFEVDResPeriods(obj, data)
        writeBlockExogneity(obj, data)
        writeCfConditions(obj, data)
        writeCfShocks(obj, data)
        writeCfBlocks(obj, data)
        writeCfIntervals(obj, data)
        writeGridSearch(obj, data)
        writeMeanAdjPrior(obj, data)
        writeRelMagnResValues(obj, data)
        writeRelMagnResperiods(obj, data)
        writeSignResValues(obj, data)
        writeSignResPeriods(obj, data)
        writeStrctshocks(obj, data)
        writeShocks(obj, data)
        writeStructShocks(obj, data)
        writeCoeffsTimeVariation(obj, data)

    end
    
end