
clear
close all

yearly = tablex.fromStruct({ ...
    "x", rand(5, 2), ...
    "y", 100*rand(5, 3), ...
    "Time", datex.span("2020", "2024")' ...
});

flat = tablex.upsample( ...
    yearly, 4, ...
    method="flat" ...
);

last = tablex.upsample( ...
    yearly, 4, ...
    method="last" ...
);

linear = tablex.upsample( ...
    yearly, 4, ...
    method="linear" ...
);

combined = tablex.upsample( ...
    yearly, 4, ...
    method=struct(x="last", y="linear") ...
);

hy = datex.Yearly();
hq = datex.Quarterly();

%figure();
%hold on
%plot(hy.decimal(yearly.Time), yearly.x, "-o", displayName="yearly");
%plot(hq.decimal(last.Time), last.x, "-o", displayName="last");

xxx = tablex.addTransformations(linear, ["log_x", "diff_*"]);

