% test_FAVAR.m
% Two-step FAVAR test using the factorTwostep.* package (the same path the
% BEARX GUI uses). The sandbox-style minnesotaFAVARTwostep.Meta(...) call
% in the original script went through favar.Meta which is broken in the
% current BEAR 6 toolbox; factorTwostep.Meta extends base.Meta directly
% and works.

clear
close all

import factorTwostep.*

percentiles = [10, 50, 90];
prctileFunc  = @(x) prctile(x, percentiles, 2);
extremesFunc = @(x) [min(x, [], 2), max(x, [], 2)];

%% Data
inputTbx = tablex.fromCsv("FAVAR.csv");

estimStart = datex.m(1960, 3 + 13);  % +13 init lags for Order=13
estimEnd   = datex.m(2001, 8);
estimSpan  = datex.span(estimStart, estimEnd);

%% Meta (factorTwostep.* API, not minnesotaFAVARTwostep.Meta)
reducibles = ["IPP","IPF","IPC","IPCD","IPCN","IPE","IPI","IPM","IPMD","IPMND", ...
    "IPMFG","IPD","IPN","IPMIN","IPUT","IP","IPXMCA","PMI","PMP","GMPYQ","GMYXPQ", ...
    "LHEL","LHELX","LHEM","LHNAG","LHUR","LHU680","LHU5","LHU14","LHU15","LHU26", ...
    "LPNAG","LP","LPGD","LPMI","LPCC","LPEM","LPED","LPEN","LPSP","LPTU","LPT", ...
    "LPFR","LPS","LPGOV","LPHRM","LPMOSA","PMEMP","GMCQ","GMCDQ","GMCNQ","GMCSQ", ...
    "GMCANQ","HSFR","HSNE","HSMW","HSSOU","HSWST","HSBR","HMOB","PMNV","PMNO", ...
    "PMDEL","MOCMQ","MSONDQ","FSNCOM","FSPCOM","FSPIN","FSPCAP","FSPUT","FSDXP", ...
    "FSPXE","EXRSW","EXRJAN","EXRUK","EXRCAN","FYGM3","FYGM6","FYGT1","FYGT5", ...
    "FYGT10","FYAAAC","FYBAAC","SFYGM3","SFYGM6","SFYGT1","SFYGT5","SFYGT10", ...
    "SFYAAAC","SFYBAAC","FM1","FM2","FM3","FM2DQ","FMFBA","FMRRA","FMRNBA", ...
    "FCLNQ","FCLBMC","CCINRV","PMCP","PWFSA","PWFCSA","PWIMSA","PWCMSA","PSM99Q", ...
    "PUNEW","PU83","PU84","PU85","PUC","PUCD","PUS","PUXF","PUXHS","PUXM","LEHCC","LEHM","HHSNTN"];

blocks = repmat("slow", 1, numel(reducibles));

meta = Meta( ...
    EndogenousNames=["FYFF"], ...
    ReducibleNames=reducibles, ...
    ReducibleBlocks=blocks, ...
    BlockType="blocks", ...
    NumFactors=struct("slow", 2), ...
    ExogenousNames=string.empty(1,0), ...
    ShockNames=string.empty(1,0), ...
    Order=13, ...
    Intercept=false, ...
    EstimationSpan=estimSpan, ...
    IdentificationHorizon=12 ...
);

%% Data holder + estimator + reduced-form model
dataH = DataHolder(meta, inputTbx);

estimatorR1 = estimator.MinnesotaFAVARTwostep(meta);
display(estimatorR1);

redModel = ReducedForm( ...
    Meta=meta, ...
    DataHolder=dataH, ...
    Estimator=estimatorR1, ...
    Dummies={} ...
);
display(redModel);

redModel.initialize();
info = redModel.presample(500);
display(info);

fprintf("\ntest_FAVAR completed.\n");
