    function y = logPostPDF(B, sigma, th, delay, thresholdvar, ...
        meanThreshold, varThreshold, Y, LX)
      y = thresholdUtils.logLik(B, sigma, th, delay, thresholdvar, Y, LX) + ...
          thresholdUtils.logPriorPDF(th, meanThreshold, varThreshold);
    end
