% Read table with custom conditioning plan
inputPath = fullfile("tables", "ConditioningPlan.xlsx");
conditioningPlan = tablex.readConditioningPlan( ...
    inputPath, ...
    timeColumn="Conditioning plan" ...
);
?PRINT_TABLE?display(conditioningPlan);
