
%% Prepare reduced-form estimator 

% Create a reduced-form estimator object
estimatorObject = estimator.?ESTIMATOR?( ...
    meta ...
    , ?ESTIMATOR_SETTINGS?
);


%% Create reduced-form model 

% Assemble a reduced-form model from the components
redModel = ReducedForm( ...
    Meta=meta ...
    , DataHolder=dataHolderObject ...
    , Estimator=estimatorObject ...
    , Dummies=dummyObjects ...
);

?PRINT_OBJECT?display(redModel);

