% Read table with custom conditioning plan
inputPath__ = fullfile("tables", "ConditioningPlan.xlsx");
conditioningPlan = tablex.readConditioningPlan( ...
    inputPath__, ...
    timeColumn="Conditioning plan" ...
);
?PRINT_TABLE?display(conditioningPlan);
