
function reminder = generateReminderParagraph()

    reminder = join([ ...
        "<p>", ...
        "Remember to press the Submit button to save your changes. ", ...
        "Otherwise, the changes will be discarded.", ...
        "</p>", ...
    ], newline());

end%

