
function axesHandle = createEmptyTile()

    axesHandle = nexttile();

    set( ...
        axesHandle ...
        , xTickLabel=[] ...
        , yTickLabel=[] ...
        , xGrid=false ...
        , yGrid=false ...
        , xColor=[1, 1, 1] ...
        , xTick=[] ...
        , yTick=[] ...
        , yColor=[1, 1, 1] ...
    );

end%

