
function textHandle = figureTitle(figureHandle, text, varargin)

    FONT_SIZE_MULTIPLIER = 1.3;

    figureFontSize = get(figureHandle, "defaultAxesFontSize");
    fontSize = FONT_SIZE_MULTIPLIER * figureFontSize;

    textHandle = annotation( ...
        figureHandle, ...
        "textBox", [0, 1, 1, 0], ...
        "fontSize", fontSize, ...
        "string", text, ...
        "horizontal", "center", ...
        "vertical", "top", ...
        "lineStyle", "none", ...
        varargin{:} ...
    );

end%

