fprintf('%s\n','%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%');
fprintf(fid,'%s\n','%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%');
fprintf('%s\n','%                                                                                                        %');
fprintf(fid,'%s\n','%                                                                                                        %');
fprintf('%s\n','%    BAYESIAN ESTIMATION, ANALYSIS AND REGRESSION (BEAR) TOOLBOX                                         %');
fprintf(fid,'%s\n','%    BAYESIAN ESTIMATION, ANALYSIS AND REGRESSION (BEAR) TOOLBOX                                         %');
fprintf('%s\n','%                                                                                                        %');
fprintf(fid,'%s\n','%                                                                                                        %');
fprintf('%s\n','%    This statistical package has been developed by the external                                         %');
fprintf(fid,'%s\n','%    This statistical package has been developed by the external                                         %');
fprintf('%s\n','%    developments division of the European Central Bank.                                                 %');
fprintf(fid,'%s\n','%    developments division of the European Central Bank.                                                 %');
fprintf('%s\n','%                                                                                                        %');
fprintf(fid,'%s\n','%                                                                                                        %');
fprintf('%s\n','%    Authors:                                                                                            %');
fprintf(fid,'%s\n','%    Authors:                                                                                            %');
fprintf('%s\n','%    Romain Legrand  									                                                 %');
fprintf(fid,'%s\n','%    Romain Legrand  									                                                 %');
fprintf('%s\n','%    Alistair Dieppe (adieppe@worldbank.org)                                                             %');
fprintf(fid,'%s\n','%    Alistair Dieppe (adieppe@worldbank.org)                                                             %');
fprintf('%s\n','%    Björn van Roye  (Bjorn.van_Roye@ecb.europa.eu)                                                      %');
fprintf(fid,'%s\n','%    Björn van Roye  (Bjorn.van_Roye@ecb.europa.eu)                                                      %');
fprintf('%s\n','%                                                                                                        %');
fprintf(fid,'%s\n','%                                                                                                        %');
fprintf('%s\n','%    Version 5.0                                                                                         %');
fprintf(fid,'%s\n','%    Version 5.0                                                                                         %');
fprintf('%s\n','%                                                                                                        %');
fprintf(fid,'%s\n','%                                                                                                        %');
fprintf('%s\n','%    The authors are grateful to the following people for valuable input                                 %');
fprintf(fid,'%s\n','%    The authors are grateful to the following people for valuable input                                 %');
fprintf('%s\n','%    and advice which contributed to improve the quality of the toolbox:                                 %');
fprintf(fid,'%s\n','%    and advice which contributed to improve the quality of the toolbox:                                 %');
fprintf('%s\n','%    Paolo Bonomolo, Mirco Balatti, Marta Banbura, Niccolo Battistini, Gabriel Bobeica, Martin Bruns,    %');
fprintf(fid,'%s\n','%    Paolo Bonomolo, Mirco Balatti, Marta Banbura, Niccolo Battistini, Gabriel Bobeica, Martin Bruns,    %');
fprintf('%s\n','%    Fabio Canova, Matteo Ciccarelli, Marek Jarocinski, Michele Lenza, Francesca Loria, Gary Koop,       %');
fprintf(fid,'%s\n','%    Fabio Canova, Matteo Ciccarelli, Marek Jarocinski, Michele Lenza, Francesca Loria, Gary Koop,       %');
fprintf('%s\n','%    Mirela Miescu, Chiara Osbat, Giorgio Primiceri, Martino Ricci, Michal Rubaszek, Barbara Rossi,      %');
fprintf(fid,'%s\n','%    Mirela Miescu, Chiara Osbat, Giorgio Primiceri, Martino Ricci, Michal Rubaszek, Barbara Rossi,      %');
fprintf('%s\n','%    Ben Schumann, Marius Schulte, Hugo Vega de la Cruz and Peter Welz.                                  %');
fprintf(fid,'%s\n','%    Ben Schumann, Marius Schulte, Hugo Vega de la Cruz and Peter Welz.                                  %');
fprintf('%s\n','%                                                                                                        %');
fprintf(fid,'%s\n','%                                                                                                        %');
fprintf('%s\n','%    These programmes are the responsibilities of the authors and not of                                 %');
fprintf(fid,'%s\n','%    These programmes are the responsibilities of the authors and not of                                 %');
fprintf('%s\n','%    the ECB and all errors and ommissions remain those of the authors.                                  %');
fprintf(fid,'%s\n','%    the ECB and all errors and ommissions remain those of the authors.                                  %');
fprintf('%s\n','%                                                                                                        %');
fprintf(fid,'%s\n','%                                                                                                        %');
fprintf('%s\n','%    Using the BEAR toolbox implies acceptance of the End User Licence                                   %');
fprintf(fid,'%s\n','%    Using the BEAR toolbox implies acceptance of the End User Licence                                   %');
fprintf('%s\n','%    Agreement and appropriate acknowledgement should be made.                                           %');
fprintf(fid,'%s\n','%    Agreement and appropriate acknowledgement should be made.                                           %');
fprintf('%s\n','%                                                                                                        %');
fprintf(fid,'%s\n','%                                                                                                        %');
fprintf('%s\n','%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%');
fprintf(fid,'%s\n','%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%');