fprintf('%s\n','%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%');
fprintf(fid,'%s\n','%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%');
fprintf('%s\n','%                                                                          %');
fprintf(fid,'%s\n','%                                                                          %');
fprintf('%s\n','%    BAYESIAN ESTIMATION, ANALYSIS AND REGRESSION (BEAR) TOOLBOX           %');
fprintf(fid,'%s\n','%    BAYESIAN ESTIMATION, ANALYSIS AND REGRESSION (BEAR) TOOLBOX           %');
fprintf('%s\n','%                                                                          %');
fprintf(fid,'%s\n','%                                                                          %');
fprintf('%s\n','%    This statistical package has been developed by the external           %');
fprintf(fid,'%s\n','%    This statistical package has been developed by the external           %');
fprintf('%s\n','%    developments division of the European Central Bank.                   %');
fprintf(fid,'%s\n','%    developments division of the European Central Bank.                   %');
fprintf('%s\n','%                                                                          %');
fprintf(fid,'%s\n','%                                                                          %');
fprintf('%s\n','%    Authors:                                                              %');
fprintf(fid,'%s\n','%    Authors:                                                              %');
fprintf('%s\n','%    Alistair Dieppe (alistair.dieppe@ecb.europa.eu)                       %');
fprintf(fid,'%s\n','%    Alistair Dieppe (alistair.dieppe@ecb.europa.eu)                       %');
fprintf('%s\n','%    Björn van Roye  (Bjorn.van_Roye@ecb.europa.eu)                        %');
fprintf(fid,'%s\n','%    Björn van Roye  (Bjorn.van_Roye@ecb.europa.eu)                        %');
fprintf('%s\n','%                                                                          %');
fprintf(fid,'%s\n','%                                                                          %');
fprintf('%s\n','%    Version 5.0                                                           %');
fprintf(fid,'%s\n','%    Version 5.0                                                           %');
fprintf('%s\n','%                                                                          %');
fprintf(fid,'%s\n','%                                                                          %');
fprintf('%s\n','%    The updated version 5 of BEAR has benefitted from contributions from  %');
fprintf(fid,'%s\n','% The updated version 5 of BEAR has benefitted from contributions from     %');  
fprintf('%s\n','%       Boris Blagov, Marius Schulte and Ben Schumann.                     %');
fprintf(fid,'%s\n','%   Boris Blagov, Marius Schulte and Ben Schumann.                         %');
fprintf('%s\n','%                                                                          %');
fprintf(fid,'%s\n','%                                                                          %');
fprintf('%s\n','%      This version builds-upon previous versions where Romain Legrand was  %');
fprintf(fid,'%s\n','%  This version builds-upon previous versions where Romain Legrand was     %');
fprintf('%s\n','%       instrumental in developing BEAR.                                    %');
fprintf(fid,'%s\n','%   instrumental in developing BEAR.                                       %');
fprintf(fid,'%s\n','%                                                                          %');
fprintf('%s\n','%    The authors are grateful to the following people for valuable input   %');
fprintf(fid,'%s\n','%    The authors are grateful to the following people for valuable input   %');
fprintf('%s\n','%    and advice which contributed to improve the quality of the toolbox:   %');
fprintf(fid,'%s\n','%    and advice which contributed to improve the quality of the toolbox:   %');
fprintf('%s\n','%    Paolo Bonomolo, Mirco Balatti, Marta Banbura, Niccolo Battistini,     %');
fprintf(fid,'%s\n','%    Paolo Bonomolo, Mirco Balatti, Marta Banbura, Niccolo Battistini,     %');
fprintf('%s\n','%	 Gabriel Bobeica, Martin Bruns, Fabio Canova, Matteo Ciccarelli,       %');
fprintf(fid,'%s\n','%	 Gabriel Bobeica, Martin Bruns, Fabio Canova, Matteo Ciccarelli,       %');
fprintf('%s\n','%    Marek Jarocinski, Michele Lenza, Francesca Loria, Mirela Miescu,      %');
fprintf(fid,'%s\n','%    Marek Jarocinski, Michele Lenza, Francesca Loria, Mirela Miescu,      %');
fprintf('%s\n','%    Gary Koop, Chiara Osbat, Giorgio Primiceri, Martino Ricci,            %');
fprintf(fid,'%s\n','%    Gary Koop, Chiara Osbat, Giorgio Primiceri, Martino Ricci,            %');
fprintf('%s\n','%    Michal Rubaszek, Barbara Rossi, Fabian Schupp,                        %');
fprintf(fid,'%s\n','%    Michal Rubaszek, Barbara Rossi, Fabian Schupp,                        %');
fprintf('%s\n','%    Peter Welz and Hugo Vega de la Cruz. 						           %');
fprintf(fid,'%s\n','%    Peter Welz and Hugo Vega de la Cruz. 						           %');
fprintf('%s\n','%                                                                          %');
fprintf(fid,'%s\n','%                                                                          %');
fprintf('%s\n','%    These programmes are the responsibilities of the authors and not of   %');
fprintf(fid,'%s\n','%    These programmes are the responsibilities of the authors and not of   %');
fprintf('%s\n','%    the ECB and all errors and ommissions remain those of the authors.    %');
fprintf(fid,'%s\n','%    the ECB and all errors and ommissions remain those of the authors.    %');
fprintf('%s\n','%                                                                          %');
fprintf(fid,'%s\n','%                                                                          %');
fprintf('%s\n','%    Using the BEAR toolbox implies acceptance of the End User Licence     %');
fprintf(fid,'%s\n','%    Using the BEAR toolbox implies acceptance of the End User Licence     %');
fprintf('%s\n','%    Agreement and appropriate acknowledgement should be made.             %');
fprintf(fid,'%s\n','%    Agreement and appropriate acknowledgement should be made.             %');
fprintf('%s\n','%                                                                          %');
fprintf(fid,'%s\n','%                                                                          %');
fprintf('%s\n','%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%');
fprintf(fid,'%s\n','%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%');