env:
  DOCMAKER_GITHUB_TOKEN: ${{ secrets.DOCMAKER_GITHUB_TOKEN }}

# This is a basic workflow to help you get started with MATLAB Actions

name: Test and Package BEAR

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events for release branches
  push:
    branches: [ master, BEAR6-staging ]
    tags:
      - "v*.*.*"
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    name: Test and package BEAR
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    outputs:
      tests_passed: ${{ steps.run-tests.outcome == 'success' }}
    permissions:
      contents: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v7
      
      # Sets up MATLAB on the GitHub Actions runner
      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v3
        with:
          products: Text_Analytics_Toolbox Statistics_and_Machine_Learning_Toolbox Optimization_Toolbox
      
      - name: Start a display server for jobs running on Linux
        run: |
          sudo apt-get install -y xvfb
          Xvfb :99 &
          echo "DISPLAY=:99" >> $GITHUB_ENV
      
      - name: Run buildtool test
        id: run-tests
        continue-on-error: true
        uses: matlab-actions/run-build@v3
        with:
          tasks: check test

      - name: Upload Pages artifact
        if: always()
        uses: actions/upload-pages-artifact@v5
        with:
          path: public/

      # Runs a set of commands using the runners shell
      - name: Package Toolbox
        uses: matlab-actions/run-build@v3
        with:
          tasks: archive
          build-options: -skip check -skip test
          generate-summary: true

      - name: Upload toolbox artifact
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-artifact@v7
        with:
          name: BEARXToolbox-mltbx
          path: releases/BEARToolbox.mltbx
          if-no-files-found: error
  
  release:
    needs:
      - build
    if: startsWith(github.ref, 'refs/tags/') && needs.build.outputs.tests_passed == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download toolbox artifact
        uses: actions/download-artifact@v8
        with:
          name: BEARXToolbox-mltbx
          path: releases
      - name: Create GitHub release
        uses: softprops/action-gh-release@v3
        with:
          files: releases/BEARToolbox.mltbx
          fail_on_unmatched_files: true
          generate_release_notes: true
