env:
  DOCMAKER_GITHUB_TOKEN: ${{ secrets.DOCMAKER_GITHUB_TOKEN }}

name: BEAR CI

on:
  push:
    branches: [ master, BEAR6-staging ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    name: Test and package BEAR
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v7

      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v3
        with:
          products: Text_Analytics_Toolbox Statistics_and_Machine_Learning_Toolbox Optimization_Toolbox

      - name: Start a display server for jobs running on Linux
        run: |
          sudo apt-get install -y xvfb
          Xvfb :99 &
          echo "DISPLAY=:99" >> $GITHUB_ENV

      - name: Run buildtool test
        uses: matlab-actions/run-build@v3
        with:
          tasks: doc

      - name: Package Toolbox
        uses: matlab-actions/run-build@v3
        with:
          tasks: archive
          build-options: -skip test
          generate-summary: true

      - name: Upload toolbox artifact
        uses: actions/upload-artifact@v7
        with:
          name: BEARXToolbox-mltbx
          path: releases/BEARtoolbox.mltbx
          if-no-files-found: error

      - name: Upload Pages artifact
        if: always()
        uses: actions/upload-pages-artifact@v5
        with:
          path: public/
